"""
Tests for quantum random number generation module

Unit tests for the QRNG functionality.
"""

import unittest
from unittest.mock import Mock, patch
import sys
import os

# Add src to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from app.core.qrng import QuantumRandomGenerator


class TestQuantumRandomGenerator(unittest.TestCase):
    """Test cases for QuantumRandomGenerator class."""
    
    def setUp(self):
        """Set up test fixtures."""
        self.qrng = QuantumRandomGenerator()
    
    def test_init(self):
        """Test QuantumRandomGenerator initialization."""
        self.assertIsNotNone(self.qrng)
        self.assertIsNotNone(self.qrng.backend)
        self.assertEqual(self.qrng.shots, 1024)
        self.assertIsInstance(self.qrng.quantum_available, bool)
    
    def test_generate_random_bytes_basic(self):
        """Test basic random bytes generation."""
        num_bytes = 32
        result = self.qrng.generate_random_bytes(num_bytes)
        
        self.assertIsInstance(result, bytes)
        self.assertEqual(len(result), num_bytes)
    
    def test_generate_random_bytes_various_sizes(self):
        """Test random bytes generation with various sizes."""
        test_sizes = [1, 16, 32, 64, 128, 256]
        
        for size in test_sizes:
            with self.subTest(size=size):
                result = self.qrng.generate_random_bytes(size)
                self.assertIsInstance(result, bytes)
                self.assertEqual(len(result), size)
    
    def test_generate_random_bytes_uniqueness(self):
        """Test that generated bytes are unique across calls."""
        num_bytes = 32
        results = []
        
        # Generate multiple samples
        for _ in range(10):
            result = self.qrng.generate_random_bytes(num_bytes)
            results.append(result)
        
        # Check that all samples are unique
        unique_results = set(results)
        self.assertEqual(len(unique_results), len(results))
    
    def test_generate_quantum_key(self):
        """Test quantum key generation."""
        # Test default key size
        key = self.qrng.generate_quantum_key()
        self.assertIsInstance(key, bytes)
        self.assertEqual(len(key), 32)  # Default AES-256 key size
        
        # Test custom key size
        custom_size = 64
        key = self.qrng.generate_quantum_key(custom_size)
        self.assertIsInstance(key, bytes)
        self.assertEqual(len(key), custom_size)
    
    def test_quantum_key_uniqueness(self):
        """Test that generated keys are unique."""
        keys = []
        
        # Generate multiple keys
        for _ in range(10):
            key = self.qrng.generate_quantum_key()
            keys.append(key)
        
        # Check that all keys are unique
        unique_keys = set(keys)
        self.assertEqual(len(unique_keys), len(keys))
    
    @patch('app.core.qrng.execute')
    def test_quantum_backend_fallback(self, mock_execute):
        """Test fallback to cryptographic random when quantum fails."""
        # Make quantum execution fail
        mock_execute.side_effect = Exception("Quantum backend error")
        
        # Create new instance to trigger the fallback
        qrng = QuantumRandomGenerator()
        result = qrng.generate_random_bytes(32)
        
        self.assertIsInstance(result, bytes)
        self.assertEqual(len(result), 32)
    
    def test_test_randomness(self):
        """Test randomness quality testing."""
        sample_size = 1000
        test_results = self.qrng.test_randomness(sample_size)
        
        # Check that all expected metrics are present
        expected_keys = ['sample_size', 'chi_square', 'entropy', 'max_entropy', 'uniformity_score']
        for key in expected_keys:
            self.assertIn(key, test_results)
        
        # Check basic properties
        self.assertEqual(test_results['sample_size'], sample_size)
        self.assertGreaterEqual(test_results['entropy'], 0)
        self.assertLessEqual(test_results['entropy'], test_results['max_entropy'])
        self.assertGreaterEqual(test_results['uniformity_score'], 0)
        self.assertLessEqual(test_results['uniformity_score'], 1)
    
    def test_expand_entropy(self):
        """Test entropy expansion functionality."""
        seed = b"short_seed"
        target_length = 64
        
        result = self.qrng._expand_entropy(seed, target_length)
        
        self.assertIsInstance(result, bytes)
        self.assertEqual(len(result), target_length)
    
    def test_expand_entropy_deterministic(self):
        """Test that entropy expansion is deterministic for same input."""
        seed = b"test_seed"
        target_length = 32
        
        result1 = self.qrng._expand_entropy(seed, target_length)
        result2 = self.qrng._expand_entropy(seed, target_length)
        
        self.assertEqual(result1, result2)
    
    def test_expand_entropy_different_seeds(self):
        """Test that different seeds produce different results."""
        target_length = 32
        
        result1 = self.qrng._expand_entropy(b"seed1", target_length)
        result2 = self.qrng._expand_entropy(b"seed2", target_length)
        
        self.assertNotEqual(result1, result2)


class TestQuantumRandomGeneratorIntegration(unittest.TestCase):
    """Integration tests for QuantumRandomGenerator."""
    
    def test_large_random_generation(self):
        """Test generation of large amounts of random data."""
        qrng = QuantumRandomGenerator()
        
        # Test generating larger amounts of data
        large_sizes = [1024, 2048, 4096]
        
        for size in large_sizes:
            with self.subTest(size=size):
                result = qrng.generate_random_bytes(size)
                self.assertEqual(len(result), size)
    
    def test_concurrent_generation(self):
        """Test concurrent random number generation."""
        import threading
        
        qrng = QuantumRandomGenerator()
        results = []
        errors = []
        
        def generate_random():
            try:
                result = qrng.generate_random_bytes(32)
                results.append(result)
            except Exception as e:
                errors.append(e)
        
        # Create multiple threads
        threads = []
        for _ in range(10):
            thread = threading.Thread(target=generate_random)
            threads.append(thread)
            thread.start()
        
        # Wait for all threads to complete
        for thread in threads:
            thread.join()
        
        # Check results
        self.assertEqual(len(errors), 0, f"Errors occurred: {errors}")
        self.assertEqual(len(results), 10)
        
        # Check that all results are unique
        unique_results = set(results)
        self.assertEqual(len(unique_results), len(results))
    
    def test_randomness_quality_statistics(self):
        """Test statistical quality of generated random numbers."""
        qrng = QuantumRandomGenerator()
        
        # Generate a reasonably large sample
        sample_size = 10000
        test_results = qrng.test_randomness(sample_size)
        
        # Basic statistical checks
        self.assertGreater(test_results['entropy'], 7.0, "Entropy should be high")
        self.assertGreater(test_results['uniformity_score'], 0.9, "Distribution should be fairly uniform")
        
        # Chi-square test should not indicate extreme bias
        # For 255 degrees of freedom, critical value at 0.05 significance is ~293
        self.assertLess(test_results['chi_square'], 400, "Chi-square should not indicate extreme bias")


if __name__ == '__main__':
    unittest.main()